version: '3.9'

services:
  api:
    container_name: products_management
    build: .
    ports:
      - 3333:3000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=products_management
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d products_management']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db_products_management:/var/lib/postgresql/data
volumes:
  db_products_management:
    driver: local